
logging:
  level:
    ROOT: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8081
  error:
    include-stacktrace: always

spring:
  application:
    name: mentee-power-crm

gg:
  jte:
    templateLocation: src/main/jte
    developmentMode: true



