
logging:
  level:
    ROOT: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8081
  error:
    include-stacktrace: always

spring:
  application:
    name: mentee-power-crm
  # Datasource and JPA are in application-dev.yml (PostgreSQL) and application-test.yml (H2)

gg:
  jte:
    templateLocation: src/main/jte
    developmentMode: true



