logging:
  level:
    ROOT: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8081
  error:
    include-stacktrace: always

spring:
  application:
    name: mentee-power-crm
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
  # Datasource and JPA are in application-dev.yml (PostgreSQL) and application-test.yml (H2)
  # Для запуска с PostgreSQL используйте: --spring.profiles.active=dev
  # Для запуска без профиля будет использоваться InMemoryLeadRepository

gg:
  jte:
    templateLocation: src/main/jte
    developmentMode: true



